from sklearn.preprocessing import normalize
from sklearn.pipeline import Pipeline
import joblib
import os

# src/ directory and project root (one level up)
current_directory = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.dirname(current_directory)

# Load SVD model
pipeline: Pipeline = joblib.load(os.path.join(project_root, 'src', 'data', 'pipeline.joblib'))

# Take a text string and return a normalized numpy array of length 21 representing the svd embedding
def svd_search(query):
    if query.strip() == "":
        query = "Batman"
    return normalize(pipeline.transform([query]))[0]

top_terms = [
['film', 'movie', 'like', 'just', 'time', 'story', 'action', 'good', 'best', 'really'],
['action', 'movie', 'fun', 'sequel', 'franchise', 'sci', 'superhero', 'fi', 'comedy', 'summer'],
['pixar', 'animated', 'animation', 'disney', 'toy', 'funny', 'comedy', 'kids', 'story', 'family'],
['comedy', 'funny', 'carrey', 'sandler', 'movie', 'stiller', 'comedies', 'ferrell', 'laughs', 'romantic'],
['spider', 'superhero', 'man', 'marvel', 'batman', 'raimi', 'comic', 'franchise', 'action', 'book'],
['burton', 'batman', 'horror', 'depp', 'tim', 'spider', 'johnny', 'superhero', 'nolan', 'dark'],
['horror', 'spider', 'man', 'raimi', 'superhero', 'scary', 'marvel', 'scares', 'zombie', 'peele'],
['sci', 'fi', 'spielberg', 'carrey', 'spider', 'science', 'fiction', 'man', 'comedy', 'superhero'],
['spielberg', 'potter', 'harry', 'jurassic', 'steven', 'hanks', 'war', 'rowling', 'dinosaurs', 'yates'],
['potter', 'harry', 'rowling', 'carrey', 'sci', 'fi', 'yates', 'series', 'franchise', 'science'],
['carrey', 'jim', 'horror', 'action', 'war', 'liar', 'pixar', 'batman', 'furious', 'cruise'],
['tarantino', 'potter', 'scorsese', 'carrey', 'harry', 'nolan', 'pixar', 'quentin', 'batman', 'eastwood'],
['spider', 'depp', 'tarantino', 'carrey', 'man', 'cruise', 'raimi', 'pirates', 'disney', 'spielberg'],
['tarantino', 'quentin', 'disney', 'vol', 'movie', 'jurassic', 'pulp', 'carrey', 'jackson', 'spielberg'],
['tarantino', 'war', 'burton', 'comedy', 'spider', 'potter', 'pixar', 'funny', 'harry', 'sci'],
['war', 'gibson', 'disney', 'depp', 'cruise', 'smith', 'pirates', 'carrey', 'movie', 'lion'],
['sandler', 'cruise', 'adam', 'tarantino', 'kurosawa', 'samurai', 'tom', 'mission', 'batman', 'movie'],
['sandler', 'scorsese', 'adam', 'gibson', 'furious', 'pixar', 'war', 'fast', 'pacino', 'cars'],
['pixar', 'furious', 'toy', 'movie', 'smith', 'cars', 'gibson', 'burton', 'cruise', 'fast'],
['bourne', 'damon', 'war', 'disney', 'spy', 'greengrass', 'thriller', 'matt', 'bond', 'animated'],
['kurosawa', 'smith', 'gibson', 'samurai', 'mifune', 'fincher', 'washington', 'bourne', 'spielberg', 'potter'],
['depp', 'smith', 'pirates', 'bourne', 'sandler', 'pixar', 'men', 'marvel', 'caribbean', 'superhero'],
['nolan', 'pacino', 'smith', 'depp', 'pirates', 'spider', 'action', 'bay', 'wick', 'potter'],
['smith', 'scorsese', 'action', 'burton', 'bond', 'stallone', 'bourne', 'martin', 'bay', 'pixar'],
['smith', 'furious', 'disney', 'scorsese', 'fast', 'cruise', 'diesel', 'potter', 'cars', 'animated'],
['bourne', 'smith', 'nolan', 'war', 'damon', 'spider', 'movie', 'kurosawa', 'hangover', 'trilogy'],
['gibson', 'mel', 'depp', 'pirates', 'bergman', 'nolan', 'shyamalan', 'tarantino', 'caribbean', 'superhero'],
['fincher', 'gibson', 'pitt', 'smith', 'cruise', 'mel', 'jurassic', 'sequel', 'david', 'scorsese'],
['bond', 'craig', 'smith', 'james', 'terminator', 'skyfall', 'daniel', 'eastwood', 'royale', 'cameron'],
['washington', 'denzel', 'scott', 'sequel', 'coen', 'jackson', 'wars', 'lee', 'coens', 'hobbit'],
['matrix', 'shyamalan', 'wick', 'eastwood', 'jackson', 'reeves', 'hobbit', 'smith', 'trilogy', 'keanu'],
['terminator', 'eastwood', 'cameron', 'sequel', 'hanks', 'schwarzenegger', 'bourne', 'clint', 'jurassic', 'shyamalan'],
['pacino', 'marvel', 'shyamalan', 'thor', 'burton', 'godfather', 'kubrick', 'sequel', 'nolan', 'ant'],
['shyamalan', 'jackson', 'hobbit', 'willis', 'tolkien', 'nolan', 'transformers', 'frodo', 'hanks', 'unbreakable'],
['shyamalan', 'transformers', 'bay', 'men', 'wolverine', 'kubrick', 'ferrell', 'twilight', 'jackman', 'michael'],
['transformers', 'bay', 'ocean', 'nolan', 'toro', 'heist', 'soderbergh', 'jurassic', 'eastwood', 'zombie'],
['pacino', 'hanks', 'eastwood', 'transformers', 'bay', 'stiller', 'bond', 'hangover', 'affleck', 'phillips'],
['zombie', 'shyamalan', 'ocean', 'soderbergh', 'heist', 'sequel', 'willis', 'jumanji', 'eastwood', 'game'],
['shyamalan', 'pacino', 'zombie', 'jurassic', 'anderson', 'wright', 'dinosaurs', 'shaun', 'smith', 'pegg'],
['matrix', 'shyamalan', 'coen', 'coens', 'hanks', 'jurassic', 'hangover', 'war', 'nolan', 'brothers'],
['stiller', 'jurassic', 'eastwood', 'affleck', 'ben', 'kubrick', 'dinosaurs', 'jack', 'matrix', 'park'],
['coen', 'coens', 'pacino', 'trek', 'ocean', 'abrams', 'soderbergh', 'brothers', 'fargo', 'star'],
['twilight', 'jurassic', 'nolan', 'bella', 'edward', 'eastwood', 'thor', 'vampire', 'dinosaurs', 'hunger'],
['ferrell', 'jurassic', 'men', 'wolverine', 'matrix', 'jackman', 'hangover', 'mckay', 'dinosaurs', 'singer'],
['wars', 'trek', 'star', 'wick', 'ferrell', 'abrams', 'disney', 'jurassic', 'lucas', 'eastwood'],
['ferrell', 'nolan', 'stiller', 'lee', 'washington', 'denzel', 'wars', 'matrix', 'mckay', 'trek'],
['ferrell', 'kubrick', 'mckay', 'bergman', 'pacino', 'snyder', 'superman', 'ritchie', 'mcdonagh', 'ocean'],
['mcdonagh', 'ferrell', 'wick', 'affleck', 'ocean', 'war', 'hunger', 'soderbergh', 'crowe', 'lawrence'],
['lee', 'hanks', 'affleck', 'spike', 'jurassic', 'disney', 'terminator', 'hulk', 'ang', 'peele'],
['matrix', 'bergman', 'ritchie', 'wolverine', 'disney', 'affleck', 'jackman', 'aronofsky', 'crowe', 'kaji'],
['bergman', 'mcdonagh', 'scott', 'twilight', 'wick', 'tarkovsky', 'men', 'aronofsky', 'bella', 'alien'],
['kubrick', 'hanks', 'wright', 'bay', 'transformers', 'men', 'affleck', 'stanley', 'pegg', 'hughes'],
['mcdonagh', 'ritchie', 'hanks', 'matrix', 'ferrell', 'trek', 'chaplin', 'wars', 'holmes', 'farrell'],
['toro', 'hellboy', 'ritchie', 'del', 'kubrick', 'hughes', 'guillermo', 'anderson', 'teen', 'eastwood'],
['anderson', 'eastwood', 'thor', 'spielberg', 'mcdonagh', 'wes', 'hangover', 'crowe', 'bay', 'matrix'],
['affleck', 'anderson', 'hangover', 'bale', 'wes', 'bergman', 'robin', 'phillips', 'williams', 'hughes'],
['affleck', 'love', 'ritchie', 'ferrell', 'ozu', 'scott', 'alien', 'sequel', 'wong', 'dragon'],
['bergman', 'jones', 'batman', 'indiana', 'bale', 'ferrell', 'raiders', 'romantic', 'lee', 'ford'],
['aronofsky', 'shrek', 'affleck', 'wick', 'chaplin', 'gyllenhaal', 'apes', 'thriller', 'neeson', 'dawn'],
['anderson', 'men', 'aronofsky', 'ferrell', 'eastwood', 'wes', 'jolie', 'reynolds', 'hunger', 'lawrence'],
['peele', 'wick', 'kaji', 'ritchie', 'hughes', 'transformers', 'john', 'bale', 'stiller', 'wars'],
['snyder', 'apes', 'mcdonagh', 'chaplin', 'superman', 'ant', 'nolan', 'jolie', 'hughes', 'bergman'],
['ozu', 'thor', 'eda', 'kore', 'apes', 'family', 'neeson', 'disney', 'toy', 'fincher'],
['stiller', 'neeson', 'hannibal', 'jolie', 'hopkins', 'hangover', 'ferrell', 'lecter', 'liam', 'hitchcock']
]
bottom_terms = [
['shite', 'botox', 'pitied', 'yukio', 'wallowed', 'corset', 'gushers', 'peeves', 'liken', 'demure'],
['film', 'que', 'life', 'la', 'love', 'war', 'und', 'der', 'kurosawa', 'bergman'],
['action', 'sci', 'fi', 'thriller', 'horror', 'war', 'cruise', 'science', 'fiction', 'terminator'],
['pixar', 'action', 'animation', 'sci', 'fi', 'animated', 'disney', 'spielberg', 'toy', 'war'],
['horror', 'sci', 'fi', 'thriller', 'pixar', 'spielberg', 'science', 'scary', 'fiction', 'alien'],
['action', 'pixar', 'comedy', 'furious', 'cruise', 'fast', 'funny', 'sandler', 'que', 'stiller'],
['burton', 'depp', 'action', 'tim', 'batman', 'carrey', 'sci', 'furious', 'fi', 'cruise'],
['potter', 'horror', 'furious', 'harry', 'action', 'franchise', 'tarantino', 'series', 'rowling', 'fast'],
['sci', 'fi', 'action', 'pixar', 'spider', 'thriller', 'terminator', 'carrey', 'science', 'scott'],
['spielberg', 'tarantino', 'war', 'cruise', 'action', 'hanks', 'scorsese', 'depp', 'tom', 'thriller'],
['sci', 'fi', 'spider', 'sandler', 'movie', 'smith', 'romantic', 'love', 'science', 'adam'],
['horror', 'sequel', 'furious', 'burton', 'spielberg', 'que', 'jurassic', 'action', 'fast', 'fun'],
['batman', 'war', 'nolan', 'superhero', 'superman', 'men', 'pixar', 'marvel', 'sandler', 'comic'],
['cruise', 'bourne', 'pixar', 'thriller', 'tom', 'scorsese', 'bond', 'damon', 'mission', 'spider'],
['movie', 'disney', 'smith', 'batman', 'nolan', 'book', 'carrey', 'superman', 'love', 'lion'],
['batman', 'nolan', 'spielberg', 'pixar', 'tarantino', 'bourne', 'furious', 'jurassic', 'damon', 'spider'],
['scorsese', 'depp', 'pacino', 'martin', 'pirates', 'sequel', 'niro', 'smith', 'hangover', 'dicaprio'],
['cruise', 'kurosawa', 'samurai', 'smith', 'tom', 'mifune', 'comedy', 'funny', 'disney', 'mission'],
['sandler', 'disney', 'bourne', 'scorsese', 'kurosawa', 'animated', 'nolan', 'damon', 'adam', 'animation'],
['kurosawa', 'scorsese', 'samurai', 'mifune', 'pixar', 'pacino', 'akira', 'cruise', 'martin', 'depp'],
['cruise', 'scorsese', 'bond', 'franchise', 'mission', 'tarantino', 'tom', 'pirates', 'jack', 'cameron'],
['gibson', 'batman', 'nolan', 'spider', 'disney', 'scorsese', 'cameron', 'terminator', 'furious', 'action'],
['furious', 'bourne', 'kurosawa', 'marvel', 'scorsese', 'damon', 'bond', 'fast', 'thor', 'burton'],
['furious', 'nolan', 'depp', 'fincher', 'pirates', 'fast', 'pacino', 'diesel', 'caribbean', 'disney'],
['gibson', 'matrix', 'jackson', 'bourne', 'pixar', 'jurassic', 'hobbit', 'trilogy', 'terminator', 'cameron'],
['fincher', 'marvel', 'washington', 'action', 'thor', 'superhero', 'denzel', 'wick', 'coen', 'willis'],
['fincher', 'war', 'pitt', 'terminator', 'burton', 'kubrick', 'david', 'sequel', 'dragon', 'cameron'],
['washington', 'hanks', 'eastwood', 'pacino', 'denzel', 'action', 'wick', 'john', 'bourne', 'horror'],
['scorsese', 'bourne', 'cruise', 'damon', 'fincher', 'thor', 'stiller', 'transformers', 'marvel', 'jurassic'],
['terminator', 'depp', 'fincher', 'stallone', 'pirates', 'cameron', 'action', 'spielberg', 'schwarzenegger', 'zombie'],
['terminator', 'washington', 'scott', 'cameron', 'denzel', 'jurassic', 'ridley', 'crowe', 'bond', 'alien'],
['bond', 'craig', 'washington', 'scott', 'zombie', 'denzel', 'wick', 'reeves', 'pixar', 'matrix'],
['eastwood', 'batman', 'pirates', 'superman', 'zombie', 'coen', 'snyder', 'hanks', 'ferrell', 'coens'],
['matrix', 'wick', 'reeves', 'coen', 'keanu', 'zombie', 'coens', 'john', 'pacino', 'film'],
['zombie', 'smith', 'thor', 'hanks', 'eastwood', 'jackson', 'pitt', 'hobbit', 'wick', 'terminator'],
['shyamalan', 'washington', 'twilight', 'terminator', 'denzel', 'hangover', 'batman', 'men', 'hanks', 'spielberg'],
['coen', 'kubrick', 'coens', 'mcdonagh', 'jackson', 'love', 'nolan', 'lee', 'cameron', 'romantic'],
['fincher', 'transformers', 'bergman', 'bay', 'coen', 'matrix', 'coens', 'ferrell', 'jackson', 'hobbit'],
['hangover', 'hanks', 'ocean', 'matrix', 'phillips', 'kubrick', 'soderbergh', 'heist', 'downey', 'ritchie'],
['pacino', 'men', 'jackson', 'wolverine', 'hobbit', 'stallone', 'trek', 'abrams', 'tolkien', 'singer'],
['hanks', 'hangover', 'nolan', 'zombie', 'phillips', 'hughes', 'ferrell', 'toro', 'terminator', 'teen'],
['aronofsky', 'lee', 'mcdonagh', 'ritchie', 'lawrence', 'film', 'hangover', 'hunger', 'kubrick', 'spike'],
['shyamalan', 'kubrick', 'batman', 'transformers', 'wars', 'trek', 'star', 'bay', 'superman', 'aronofsky'],
['stiller', 'affleck', 'hunger', 'games', 'mcdonagh', 'lawrence', 'mockingjay', 'ben', 'bergman', 'coen'],
['anderson', 'hanks', 'matrix', 'stiller', 'pacino', 'zombie', 'jackson', 'hobbit', 'wes', 'shrek'],
['hangover', 'ritchie', 'mcdonagh', 'coen', 'coens', 'disney', 'reynolds', 'jurassic', 'pacino', 'phillips'],
['stiller', 'wolverine', 'wick', 'men', 'hanks', 'jackman', 'anderson', 'john', 'nolan', 'transformers'],
['lee', 'stallone', 'ritchie', 'eastwood', 'hangover', 'downey', 'twilight', 'kubrick', 'trek', 'spike'],
['aronofsky', 'scott', 'stallone', 'crowe', 'shrek', 'toro', 'ritchie', 'rocky', 'bale', 'jackman'],
['anderson', 'kubrick', 'hanks', 'stallone', 'wes', 'coen', 'batman', 'coens', 'smith', 'mcdonagh'],
['matrix', 'lawrence', 'hunger', 'ritchie', 'mockingjay', 'games', 'ferrell', 'thor', 'washington', 'snyder'],
['toro', 'mcdonagh', 'anderson', 'hangover', 'hellboy', 'del', 'lee', 'stallone', 'abrams', 'guillermo'],
['eastwood', 'hangover', 'jolie', 'lee', 'hughes', 'teen', 'bergman', 'wick', 'cruise', 'coen'],
['aronofsky', 'stallone', 'lee', 'gyllenhaal', 'mcdonagh', 'rocky', 'hangover', 'kaji', 'coen', 'darren'],
['hanks', 'jurassic', 'toro', 'jumanji', 'nolan', 'stiller', 'stallone', 'coen', 'coens', 'dinosaurs'],
['mcdonagh', 'jolie', 'eastwood', 'toro', 'stiller', 'angelina', 'chaplin', 'aronofsky', 'disney', 'hannibal'],
['aronofsky', 'jurassic', 'wars', 'bergman', 'disney', 'lucas', 'anderson', 'thor', 'movie', 'hughes'],
['affleck', 'washington', 'ocean', 'kubrick', 'hughes', 'soderbergh', 'stallone', 'wolverine', 'mcdonagh', 'ozu'],
['stallone', 'matrix', 'mcdonagh', 'bergman', 'hughes', 'kaji', 'rocky', 'scott', 'teen', 'disney'],
['thor', 'crowe', 'bale', 'snyder', 'stallone', 'gyllenhaal', 'rocky', 'smith', 'superman', 'boxing'],
['affleck', 'thor', 'trek', 'matrix', 'kong', 'abrams', 'hangover', 'toro', 'neeson', 'godzilla'],
['batman', 'kaji', 'hanks', 'ocean', 'kubrick', 'soderbergh', 'aronofsky', 'thor', 'toro', 'bale'],
['shrek', 'abrams', 'trek', 'kong', 'lee', 'godzilla', 'lawrence', 'dragon', 'hunger', 'mockingjay'],
['thor', 'shrek', 'washington', 'emmerich', 'bergman', 'denzel', 'eastwood', 'fincher', 'chaplin', 'godzilla']
]